import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {

  Sidebar: [
    'welcome',
    {
      type: 'category',
      label: 'MythicalDash',
      collapsed: false,
      items: [
        'MythicalDash/intro',
        'MythicalDash/install',
        'MythicalDash/createssl',
        'MythicalDash/webserver',
        'MythicalDash/congratulations',
        'MythicalDash/upgrade',
        "MythicalDash/faq",
      ]
    },
    {
      type: 'link',
      label: 'Discord Server',
      href: 'https://discord.mythicalsystems.xyz',
    },
    {
      type: 'link',
      label: 'GitHub',
      href: 'https://github.com/mythicalltd',
    },
    {
      type: 'link',
      label: 'Status',
      href: 'https://status.mythicalsystems.xyz/',
    },
    {
      type: 'link',
      label: 'Donate',
      href: '/donate',
    }
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: 
  //[{type: 'autogenerated', dirName: '.'}],

};

export default sidebars;