import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    Sidebar: [
        'welcome',
        {
            type: 'category',
            label: 'MythicalDash',
            collapsed: true,
            items: [
                'MythicalDash/intro',
                'MythicalDash/install',
                'MythicalDash/createssl',
                'MythicalDash/webserver',
                'MythicalDash/congratulations',
                'MythicalDash/upgrade',
                'MythicalDash/faq',
            ],
        },
        {
            type: 'category',
            label: 'MythicalFramework',
            collapsed: true,
            items: [
                'MythicalFramework/welcome',
                {
                    type: 'category',
                    label: 'User',
                    items: [
                        'MythicalFramework/user/install',
                        {
                            type: 'category',
                            label: 'Operating System',
                            items: ['MythicalFramework/user/os/ubuntu', 'MythicalFramework/user/os/deb'],
                        },
                        {
                            type: 'category',
                            label: 'WebServers',
                            items: [
                                'MythicalFramework/user/webservers/apache',
                                'MythicalFramework/user/webservers/nginx',
                            ],
                        },
                        'MythicalFramework/user/ssl-cert',
                    ],
                },
                {
                    type: 'category',
                    label: 'Developer',
                    items: [
                        'MythicalFramework/developer/getting-started',
                        {
                          type: 'category',
                          label: 'Developers',
                          items: [
                            'MythicalFramework/developer/developers/getting-started',
                            {
                                type: 'category',
                                label: 'Components',
                                items: [
                                    {
                                        type: 'autogenerated',
                                        dirName: 'MythicalFramework/developer/developers/components',
                                    },
                                ],
                            },
                          ],
                        },
                        {
                            type: 'category',
                            label: 'Plugins',
                            items: [
                                'MythicalFramework/developer/plugins/getting-started',
                                {
                                    type: 'category',
                                    label: 'Events',
                                    items: [
                                        {
                                            type: 'autogenerated',
                                            dirName: 'MythicalFramework/developer/plugins/events',
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            type: 'link',
            label: 'Discord Server',
            href: 'https://discord.mythicalsystems.xyz',
        },
        {
            type: 'link',
            label: 'GitHub',
            href: 'https://github.com/mythicalltd',
        },
        {
            type: 'link',
            label: 'Status',
            href: 'https://status.mythicalsystems.xyz/',
        },
        {
            type: 'link',
            label: 'Donate',
            href: '/donate',
        },
    ],
    // By default, Docusaurus generates a sidebar from the docs folder structure
};

export default sidebars;
